# Generated by Django 5.1.3 on 2024-11-22 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('flag', models.ImageField(upload_to='banderas')),
                ('photo', models.ImageField(upload_to='pilotos')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.team')),
            ],
        ),
    ]
