# Generated by Django 5.1.3 on 2024-11-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_team_points'),
        ('pilotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piloto',
            new_name='Pilot',
        ),
    ]
